"""Redaktioneller Kartensatz. Ausführen regeneriert cards.json und Abdeckung."""
import json
from pathlib import Path
root=Path(__file__).resolve().parent.parent
sources={
 'erde':{'title':'NASA: Earth Facts','url':'https://science.nasa.gov/earth/facts/'},
 'sonne':{'title':'NASA: Sun Facts','url':'https://science.nasa.gov/sun/facts/'},
 'mond':{'title':'NASA: Moon Facts','url':'https://science.nasa.gov/moon/facts/'},
 'system':{'title':'NASA: Solar System Facts','url':'https://science.nasa.gov/solar-system/solar-system-facts/'},
 'achse':{'title':'NASA: Reference Systems, Erdachse und Präzession','url':'https://science.nasa.gov/learn/basics-of-space-flight/chapter2-1/'},
 'geoid':{'title':'GFZ: Schwerefeld und Geoid','url':'https://www.gfz.de/sektion/globales-geomonitoring-und-schwerefeld/themen/regionale-und-globale-statische-schwerefeldbestimmung'},
 'tz':{'title':'IANA: Zeitzonendatenbank','url':'https://www.iana.org/time-zones'},
 'asien':{'title':'IANA: Zeitzonen und historische Regeln in Asien','url':'https://data.iana.org/time-zones/tzdb/asia'},
 'pazifik':{'title':'IANA: Pazifik, Neuseeland und Samoa','url':'https://data.iana.org/time-zones/tzdb/australasia'},
 'amerika':{'title':'IANA: Nordamerika und Grönland','url':'https://data.iana.org/time-zones/tzdb/northamerica'},
 'katla':{'title':'Smithsonian: Katla, Koordinaten','url':'https://volcano.si.edu/volcano.cfm?vn=372030'},
 'karte':{'title':'swisstopo: Koordinaten eines Ortes bestimmen','url':'https://www.swisstopo.admin.ch/de/haeufige-fragen-geodaesie-lv'}
}
goals=[];cards=[]
def section(id,title,description):
 goals.append(dict(id=id,title=title,description=description))
 global current
 current=(id,title)
def add(id,level,q,a,pages,origin='',note='',links='',status=None):
 cards.append(dict(id=id,topic=current[1],goals=[current[0]],level={'b':'basis','v':'vertieft','p':'profi'}[level],question=q,answer=a.split(' || '),pages=pages,origin=origin or current[1],note=note,links=links.split() if links else [],status=status or ('praezisiert' if note else 'abgeglichen'),image=None))
section('L01','Geografie verstehen','Fachgebiete unterscheiden, Mensch und Natur verknüpfen und räumliche Massstäbe beachten.')
add('G01','b','Was bedeutet «Geographie» wörtlich und was untersucht das Fach heute?','Geo bedeutet Erde, graphein schreiben bzw. beschreiben. Heute untersucht die Geografie räumliche Strukturen, Entwicklungen und die Beziehungen zwischen Mensch und Umwelt.','A 2–3')
add('G02','b','Was unterscheidet physische Geografie und Humangeografie?','Physische Geografie untersucht natürliche Prozesse, etwa Klima, Gewässer und Landformen. Humangeografie untersucht menschliche Raumnutzung, etwa Siedlungen, Wirtschaft, Bevölkerung und Verkehr.','A 3')
add('G03','v','Warum ist eine Überschwemmung ein Thema beider Teilgebiete?','Starkregen, Abfluss und Gelände sind natürliche Faktoren. Bebauung, versiegelte Flächen, Schutzbauten und die Gefährdung von Menschen betreffen die Humangeografie. Erst ihr Zusammenwirken erklärt das Risiko.','A 2–3',origin='Transfer aus Kapitel 1')
add('G04','b','Was bedeuten Topografie und Länderkunde?','Topografie beschreibt Lage und Gestalt der Erdoberfläche. Die traditionelle Länderkunde beschreibt einen Raum anhand von Natur, Bevölkerung und Nutzung. Moderne Geografie fragt darüber hinaus nach Prozessen, Ursachen und Verflechtungen.','A 2')
add('G05','v','Was bedeutet interdisziplinär? Nenne zwei geografische Beispiele.','Mehrere Fachgebiete tragen zur Untersuchung bei: Beim Klima helfen Physik und Chemie, bei Bevölkerungsentwicklung Mathematik und Sozialwissenschaften.','A 3')
add('G06','v','Warum sind räumliche und zeitliche Massstäbe wichtig?','Ein lokales Hochwasser dauert Stunden oder Tage; die Entstehung eines Gebirges betrifft grosse Räume und Millionen Jahre. Aussagen müssen zum betrachteten Raum und Zeitraum passen. Ein einzelner heisser Tag beweist noch keinen langfristigen Klimatrend.','A 3')
add('G07','b','Welche Sphären zeigt das Dossier, und wofür stehen sie?','Atmosphäre: Lufthülle; Hydrosphäre: Wasser; Kryosphäre: Eis und Schnee; Lithosphäre: feste äussere Gesteinshülle; Biosphäre: Bereich des Lebens. Sie beeinflussen sich gegenseitig.','A 2',origin='Abbildung 2')
add('G08','p','Wie prüfst du eine geografische Darstellung kritisch?','Prüfe Quelle und Datum, räumlichen Ausschnitt, Massstab, Legende und Messgrössen. Unterscheide Beobachtung und Erklärung. Eine alte Weltkarte dokumentiert auch den damaligen Kenntnisstand; sie ist keine genaue Darstellung der heutigen Erde.','A 2–3',origin='Methodentransfer')
section('L02','Erdgestalt','Kugel, Rotationsellipsoid und Geoid erklären und voneinander abgrenzen.')
add('E01','b','Welche Beobachtungen sprechen für eine annähernd kugelförmige Erde?','Schiffe verschwinden am Horizont zuerst mit dem Rumpf. Bei Mondfinsternissen ist der Erdschatten rund. Je nach geografischer Breite sieht man andere Sternhöhen und Sternbilder. Satellitenaufnahmen bestätigen die Form.','A 4')
add('E02','b','Was ist die Erdrotation?','Die Erde dreht sich um ihre eigene Achse. Ein mittlerer Sonnentag dauert 24 Stunden. Vom Nordpol aus gesehen erfolgt die Drehung gegen den Uhrzeigersinn, von Westen nach Osten.','A 4; B 9, 11')
add('E03','v','Wo ist die Zentrifugalwirkung am stärksten, wo am kleinsten?','Am Äquator ist der Abstand von der Rotationsachse am grössten und damit die Zentrifugalwirkung am stärksten. An den Polen ist der Abstand zur Achse null und die Wirkung verschwindet.','A 4–5')
add('E04','b','Warum beschreibt ein Rotationsellipsoid die Erde besser als eine Kugel?','Durch die Rotation ist die Erde an den Polen abgeplattet und am Äquator etwas ausgebeult. Der Äquatorradius beträgt etwa 6’378 km, der Polradius etwa 6’357 km.','A 5',origin='Erdmodelle und Abbildung')
add('E05','v','Was ist ein Geoid?','Das Geoid ist eine durch das Erdschwerefeld bestimmte Niveaufläche, die näherungsweise dem mittleren Meeresspiegel entspricht und unter den Kontinenten weitergedacht wird. Ungleiche Massenverteilung verursacht Abweichungen vom glatten Referenzellipsoid.','A 4–5',note='Das Geoid bildet keine Gebirge oder realen Hebungen des Untergrunds ab. Die farbige «Kartoffelform» ist stark überhöht.',links='geoid')
add('E06','p','Ordne Kugel, Rotationsellipsoid, Geoid und Geländeoberfläche ein.','Kugel: einfaches Modell mit gleichem Radius. Rotationsellipsoid: mathematische Näherung mit Polabplattung. Geoid: physikalische Höhenbezugsfläche des Schwerefelds. Geländeoberfläche: wirkliche Berge, Täler und Meeresböden.','A 4–5',note='Geoid und Geländeoberfläche sind nicht dasselbe.',links='geoid')
add('E07','p','Warum kann eine Massenverschiebung bei einem Erdbeben die Rotation beeinflussen?','Die Verteilung der Erdmasse beeinflusst das Trägheitsmoment. Ändert sie sich, können sich Rotationsdauer und Lage von Achsen sehr geringfügig ändern. Der Zeitungsausschnitt liefert keinen Anlass, daraus einen plötzlichen Wechsel der Jahreszeiten abzuleiten.','A 10',origin='Abbildung 10: Einordnung',note='Die Überschrift allein ersetzt keine Messwerte; das Dossier liefert hier keinen vollständigen Fachbericht.')
section('L03','Sonne & Sonnensystem','Grössenordnungen, Planeten, Entstehung und Modellgrenzen verstehen.')
add('S01','b','Wie heissen die acht Planeten in der Reihenfolge ab der Sonne?','Merkur, Venus, Erde, Mars, Jupiter, Saturn, Uranus, Neptun. Pluto gehört zu den Zwergplaneten.','A 6–8',links='system')
add('S02','b','Welche sind die inneren Gesteinsplaneten?','Merkur, Venus, Erde und Mars. Sie besitzen feste Gesteinsoberflächen.','A 7',links='system')
add('S03','b','Wie unterscheiden sich die vier äusseren Planeten?','Jupiter und Saturn sind Gasriesen. Uranus und Neptun werden als Eisriesen bezeichnet. Alle vier sind wesentlich grösser als die inneren Gesteinsplaneten und besitzen Ringsysteme.','A 7–8',note='Neptun hat ebenfalls Ringe; die Aufzählung im Dossier ist unvollständig.',links='system')
add('S04','v','Wie entstand das Sonnensystem?','Vor etwa 4,6 Milliarden Jahren verdichtete sich eine Gas- und Staubwolke. Im Zentrum entstand die Sonne, in der umgebenden Scheibe wuchsen durch Zusammenballung kleinere Körper zu Planeten heran.','A 8',links='system')
add('S05','b','Was ist der Asteroidengürtel und wo liegt er?','Ein Gebiet mit zahlreichen kleinen Körpern zwischen den Bahnen von Mars und Jupiter. Dort blieben Bausteine des frühen Sonnensystems erhalten.','A 8',links='system')
add('S06','v','Unterscheide Stern, Planet, Mond und Meteorit.','Ein Stern wie die Sonne erzeugt Energie durch Kernfusion. Ein Planet umkreist einen Stern. Ein Mond umkreist einen grösseren Körper wie einen Planeten. Ein Meteorit ist ein natürlicher Körper aus dem All, der den Boden erreicht hat.','A 7–8',note='Nicht jedes kleine Objekt im Weltraum ist ein Meteorit; im All spricht man bei kleinen Brocken von Meteoroiden.')
add('S07','b','Welche ungefähren Radien haben Sonne, Erde und Mond?','Sonne: rund 696’000 km; Erde: rund 6’371 km im Mittel; Mond: rund 1’737 km. Radius und Durchmesser dürfen nicht verwechselt werden.','A 5, 7',links='sonne mond erde')
add('S08','b','Welche mittleren Entfernungen trennen Erde, Mond und Sonne?','Erde–Mond: etwa 384’400 km. Erde–Sonne: etwa 149,6 Millionen km, rund eine astronomische Einheit. Die Abstände verändern sich während der Umläufe.','A 5, 7',links='mond erde')
add('S09','v','Wie lange braucht Licht von der Sonne zur Erde?','Mit c ≈ 300’000 km/s gilt t = s ÷ v = 149’600’000 ÷ 300’000 ≈ 499 s, also etwa 8 Minuten 19 Sekunden.','A 5',origin='Überlegungsaufgabe Lichtlaufzeit')
add('S10','v','Wie lange braucht Licht von der Erde zum Mond?','384’400 km ÷ 300’000 km/s ≈ 1,28 Sekunden für einen Weg. Für Hin- und Rückweg etwa 2,56 Sekunden.','A 5',origin='Überlegungsaufgabe Lichtlaufzeit')
add('S11','b','Was ist ein Lichtjahr?','Eine Entfernung: die Strecke, die Licht in einem Jahr zurücklegt, ungefähr 9,46 Billionen Kilometer. Es ist keine Zeiteinheit.','A 8')
add('S12','v','Warum ist der Blick in die Ferne zugleich ein Blick in die Vergangenheit?','Licht braucht Zeit. Sehen wir ein Objekt in zwei Millionen Lichtjahren Entfernung, beobachten wir Licht, das ungefähr vor zwei Millionen Jahren ausgesendet wurde.','A 8')
add('S13','b','Wie erzeugt die Sonne ihre Energie?','In ihrem Kern verschmilzt Wasserstoff zu Helium. Dabei wird Energie frei. Die Sonne besteht überwiegend aus Wasserstoff und Helium.','A 5',links='sonne')
add('S14','v','Was zeigt das Modell mit einer 1 m grossen Sonne?','Beim Massstab 1 : 1,4 Milliarden ist die Erde etwa 9,1 mm gross und rund 107 m von der Sonne entfernt. Neptun liegt rund 3,2 km entfernt. Die Abstände sind im Vergleich zu den Körpern gewaltig.','A 8',origin='Tabelle 2')
add('S15','p','Rechne im Massstab 1 : 1,4 Milliarden eine Strecke von 149,6 Millionen km um.','149’600’000 km ÷ 1’400’000’000 = 0,10686 km = 106,86 m. Erst die Einheiten vereinheitlichen, dann durch die Massstabszahl teilen.','A 8',origin='Modellrechnung')
add('S16','v','Warum sind Planetenbilder oft nicht in jeder Hinsicht massstabsgetreu?','Wären Durchmesser und Entfernungen im selben kleinen Bild korrekt skaliert, wären die Planeten kaum zu erkennen. Prüfe deshalb getrennt den Massstab der Körper und jenen der Abstände.','A 6–8')
add('S17','p','Welche Angaben im Sonnensystemtext sollte man nicht unkritisch auswendig lernen?','Die Zahl bekannter Monde verändert sich; eine undatierte feste Zahl ist ungeeignet. Die Tabelle stammt von 1999. Jupiter ist im Durchmesser ungefähr elfmal, Saturn ungefähr neunmal so gross wie die Erde. Pluto ist ein Zwergplanet.','A 7–8',note='Der Text rundet teilweise zu stark und verwendet alte Bezeichnungen. Die Lernkartei vermeidet eine schnell veraltende Mondzahl.',links='system')
add('S18','v','Wie lange braucht Sonnenlicht zu Pluto, wenn man mit den 5’966 Mio. km der Tabelle rechnet?','5’966’000’000 ÷ 300’000 = 19’886,7 s ≈ 5 h 31 min. Das ist ein Rechenwert zur alten Tabelle, keine konstante tatsächliche Entfernung.','A 7',origin='Lückentext / Tabelle 1')
add('S19','p','Warum ist eine pauschale «Grösse des Universums» problematisch?','Man muss das beobachtbare Universum vom möglicherweise viel grösseren gesamten Universum unterscheiden. Ausserdem ist zu klären, ob Radius oder Durchmesser gemeint ist. Die undifferenzierte Zahl im Dossier ist daher keine geeignete eindeutige Lernantwort.','A 8',note='Begriffsprüfung statt Übernahme einer unklaren Zahl.')
section('L04','Rechnen mit Erdgrössen','Alle neun Kennzahlen-Aufgaben mit Einheiten und Rechenweg lösen.')
for id,q,a,p in [
 ('R01','Mit dem Velo um die Erde: 40’000 km und 100 km pro Tag. Wie lange?','40’000 km ÷ 100 km/Tag = 400 Tage. Das Modell berücksichtigt weder Ozeane noch Pausen.','A 5'),
 ('R02','Zu Fuss um die Erde: 5 km/h, 8 Stunden pro Tag, 40’000 km. Wie lange?','Pro Tag: 5 × 8 = 40 km. Dauer: 40’000 ÷ 40 = 1’000 Tage, rund 2,74 Jahre.','A 5'),
 ('R03','11’000 m Tiefe bei 1,5 m/s: Wie lange dauert der Abstieg?','t = 11’000 ÷ 1,5 = 7’333,3 s. Das sind etwa 122,2 Minuten oder 2 h 2 min 13 s.','A 5'),
 ('R04','40’000 km Erdumrundung bei 900 km/h: Wie lange dauert der Flug?','40’000 ÷ 900 = 44,44 h, also etwa 44 h 27 min. Konstante Geschwindigkeit und keine Zwischenlandungen sind Modellannahmen.','A 5'),
 ('R05','Wie viele Everests ergeben einen Erddurchmesser von 12’742 km? Rechne mit 8’849 m Höhe.','8’849 m = 8,849 km. 12’742 ÷ 8,849 ≈ 1’440 Everest-Höhen. Mit dem Äquatordurchmesser ergibt sich ein geringfügig anderer Wert.','A 5'),
 ('R06','Eine Platte bewegt sich 5 cm pro Jahr. Welche Strecke ergibt das in 1 Mio. Jahren?','5 × 1’000’000 = 5’000’000 cm = 50’000 m = 50 km.','A 5'),
 ('R07','Wie viele 105 m lange Fussballfelder passen um den 40’075 km langen Äquator?','40’075 km = 40’075’000 m. Division durch 105 ergibt rund 381’667 Feldlängen. Mit gerundeten 40’000 km wären es rund 380’952.','A 5'),
 ('R08','ISS: Bahnumfang 42’500 km, Geschwindigkeit 28’000 km/h. Umlaufdauer und Umläufe pro Tag?','42’500 ÷ 28’000 = 1,518 h ≈ 91,1 Minuten. 24 ÷ 1,518 ≈ 15,8 Umläufe pro Tag.','A 5–6'),
 ('R09','Tsunami: 8’200 km Strecke bei 800 km/h. Wie lange?','8’200 ÷ 800 = 10,25 Stunden = 10 h 15 min. Die reale Geschwindigkeit hängt von der Wassertiefe ab.','A 6')]:
 add(id,'p',q,a,p,origin='Quiz Kennzahlen '+id[1:])
add('R10','v','Welche Grundformeln helfen bei den Rechenaufgaben?','Geschwindigkeit v = s ÷ t; Zeit t = s ÷ v; Strecke s = v × t. Achte auf gleiche Einheiten: 1 km = 1’000 m, 1 h = 3’600 s. Dezimale Stunden sind nicht Stunden und Minuten: 0,25 h = 15 min.','A 5–6; B 8')
section('L05','Himmelsrichtungen & Hemisphären','Orte und Kontinente den Halbkugeln zuordnen und Positionen vergleichen.')
add('H01','b','Was bedeuten Orient und Okzident? Wo steht die Mittagssonne in Mitteleuropa?','Orient bezeichnet den Osten bzw. das Morgenland, Okzident den Westen bzw. das Abendland. Bei ihrem täglichen Höchststand steht die Sonne in Mitteleuropa im Süden.','B 1')
add('H02','b','Wie werden die vier Hemisphären abgegrenzt?','Der Äquator trennt Nord- und Südhalbkugel. Nullmeridian und 180°-Meridian begrenzen Ost- und Westhalbkugel. Ostlängen liegen auf der östlichen, Westlängen auf der westlichen Hemisphäre.','B 1–2')
add('H03','b','Welche Hemisphäre hat mehr Land, und welche zwei Kontinente liegen ganz südlich des Äquators?','Die Nordhalbkugel besitzt mehr Landfläche. Australien und Antarktika liegen vollständig südlich des Äquators. Südamerika und Afrika werden vom Äquator geschnitten.','B 1',origin='Hemisphären, Fragen 1–2')
add('H04','b','Welche liegen östlich von Greenwich: Barcelona, Bordeaux, New York, Paris, Lima, Wellington, Hongkong, Honolulu?','Barcelona, Paris, Wellington und Hongkong liegen auf der östlichen Hemisphäre. Bordeaux, New York, Lima und Honolulu liegen westlich von Greenwich.','B 1',origin='Hemisphären, Frage 3')
add('H05','b','Welche liegen südlich: Kairo, Rio, Kalkutta, Johannesburg, Canberra, Miami, Antananarivo, Bogotá?','Rio de Janeiro, Johannesburg, Canberra und Antananarivo liegen auf der Südhalbkugel. Die anderen genannten Städte liegen auf der Nordhalbkugel.','B 1',origin='Hemisphären, Frage 4')
add('H06','b','In welchen Halbkugeln liegt der grösste Teil Afrikas und Südamerikas?','Afrika liegt überwiegend nördlich des Äquators und östlich von Greenwich. Südamerika liegt überwiegend südlich des Äquators und vollständig auf der westlichen Hemisphäre.','B 1',origin='Hemisphären, Fragen 5–6')
add('H07','v','Auf welcher Längen-Hemisphäre liegen Europa und Russland überwiegend?','Beide überwiegend auf der östlichen Hemisphäre. Ein kleiner Teil Russlands reicht über den 180°-Meridian in die westliche Hemisphäre. Politische Begriffe wie «der Westen» bezeichnen etwas anderes.','B 1',origin='Hemisphären, Fragen 7–8')
for id,city,result in [('H08','Jerusalem','Nord und Ost'),('H09','Madrid','Nord und West'),('H10','Wellington','Süd und Ost'),('H11','Jakarta','Süd und Ost'),('H12','Honolulu','Nord und West'),('H13','Lima','Süd und West'),('H14','Nairobi','Süd und Ost'),('H15','Tokyo','Nord und Ost'),('H16','Havanna','Nord und West'),('H17','Dakar','Nord und West')]:
 add(id,'b',f'In welchen Hemisphären liegt {city}?',f'{city} liegt in den Hemisphären {result}. Entscheidend sind Breite relativ zum Äquator und Länge relativ zu Greenwich.', 'B 7',origin='Posten 3: Hemisphären')
add('H18','v','Welche Stadt liegt südlicher: London/Hamburg, Zürich/Toronto, Rom/Madrid, Hongkong/Mumbai?','London; Toronto; Madrid; Mumbai. Auf der Nordhalbkugel bedeutet der kleinere nördliche Breitengrad die südlichere Lage.','B 7',origin='Posten 3: südlicher')
add('H19','v','Welche Stadt liegt östlicher: Zürich/Tunis, Moskau/Jerusalem, Port-au-Prince/Santiago, Istanbul/Pretoria?','Tunis; Moskau; Santiago de Chile; Istanbul. Bei westlichen Längen ist die kleinere absolute Gradzahl näher an Greenwich und damit östlicher.','B 7',origin='Posten 3: östlicher')
section('L06','Gradnetz & Koordinaten','Breite und Länge lesen, umrechnen, auf Karten messen und Gegenpunkte berechnen.')
add('K01','b','Was messen geografische Breite und Länge?','Breite misst den Winkelabstand vom Äquator nach Norden oder Süden (0° bis 90°). Länge misst den Winkelabstand vom Nullmeridian nach Osten oder Westen (0° bis 180°).','B 1–4')
add('K02','b','Was unterscheidet Breitenkreise und Meridiane?','Breitenkreise verlaufen parallel zum Äquator und werden zu den Polen kleiner. Meridiane verlaufen von Pol zu Pol und sind gleich lange Halbkreise; jeweils zwei gegenüberliegende bilden einen ganzen Längenkreis.','B 1–3',note='Ein Meridian ist präzise ein Halbkreis, auch wenn das Dossier «Kreis» und «Meridian» teilweise gleichsetzt.')
add('K03','b','Wo liegt der Nullmeridian und warum gerade dort?','Der historische Nullmeridian verläuft durch Greenwich bei London. Seine Wahl ist eine internationale Konvention von 1884, keine naturgegebene Grenze.','B 2–3')
add('K04','b','Wie liest du 52° N / 50° E?','52 Grad nördliche Breite und 50 Grad östliche Länge. Zuerst wird die Breite, dann die Länge angegeben. Der Punkt liegt auf der Nord- und Osthalbkugel.','B 4')
add('K05','b','Wie hängen Grad, Winkelminuten und Winkelsekunden zusammen?','1° = 60′ und 1′ = 60″. Deshalb gilt 1° = 3’600″. Winkelminuten beschreiben einen Winkel und sind hier keine Zeitminuten.','B 4')
add('K06','v','Wandle 47,3° N und 9,083333° E in Grad und Minuten um.','47,3° = 47° + 0,3 × 60′ = 47°18′ N. 9,083333° ≈ 9°05′ E. Das sind die in der Postenaufgabe verwendeten Koordinaten der Kanti.','B 4, 7')
add('K07','v','Wandle 48°51′04″ N und 2°20′09″ E in Dezimalgrade um.','48 + 51/60 + 4/3’600 ≈ 48,851111° N. 2 + 20/60 + 9/3’600 ≈ 2,335833° E.','B 4',origin='Louvre-Beispiel')
add('K08','p','Wandle 48,86° N und 2,34° E in Grad, Minuten und Sekunden um.','48,86° = 48°51′36″ N; 2,34° = 2°20′24″ E. Erst den Dezimalrest mit 60 multiplizieren, dann den Rest der Minuten nochmals mit 60.','B 4',note='Die gerundeten Paris-Werte sind nicht identisch mit den genaueren Louvre-Koordinaten im selben Text.')
add('K09','v','Wie bestimmt man die Koordinaten eines Ortes zwischen Gradnetzlinien?','Miss seinen relativen Abstand zwischen zwei benachbarten Breitenlinien und getrennt zwischen zwei Meridianen. Addiere den entsprechenden Anteil des Gradintervalls zum Ausgangswert. Rechne den Dezimalrest anschliessend in Minuten und Sekunden um.','B 4–5',origin='Altdorf und Chur: Methode')
add('K10','p','Ein Ort liegt 30 % von 46° N Richtung 47° N und 60 % von 8° E Richtung 9° E. Welche Koordinaten?','46,3° N / 8,6° E = 46°18′ N / 8°36′ E. Die beiden Richtungen werden getrennt interpoliert.','B 4–5',origin='Zusatzübung zur Kartenmessung')
add('K11','p','Welche Grössenordnung sollte die Kartenmessung für Altdorf und Chur ergeben?','Altdorf UR liegt ungefähr bei 46,88° N / 8,64° E, Chur ungefähr bei 46,85° N / 9,53° E. Das sind gerundete Orientierungswerte; eine exakte Lösung benötigt einen eindeutig gewählten Punkt, etwa Bahnhof oder Ortszentrum.','B 4–5',note='Kein fingierter Messwert aus der Abbildung: Kartenmassstab, Messgenauigkeit und Bezugspunkt begrenzen das Resultat.',links='karte')
add('K12','p','Wo liegt der Gegenpunkt von 47°18′ N / 9°05′ E?','47°18′ S / 170°55′ W. Breite: Nord wird Süd. Länge: 180° − 9°05′ = 170°55′, Ost wird West. Der Punkt liegt im Südpazifik südöstlich von Neuseeland, dem nächstgelegenen Staat.','B 7',origin='Posten 4: Tiefbau an der Kanti')
add('K13','p','Wie gross ist der Abstand zwischen zwei ganzgradigen Breitenkreisen? Und zwischen zwei Bogenminuten Breite?','Mit 40’000 km Meridianumfang: 40’000 ÷ 360 ≈ 111,11 km pro Grad. Pro Winkelminute: 111,11 ÷ 60 ≈ 1,852 km. Das ist näherungsweise eine Seemeile.','B 8',origin='Posten 6')
add('K14','p','Wie schnell bewegt sich ein Punkt am Äquator durch die Erdrotation?','40’000 km ÷ 24 h ≈ 1’667 km/h, mit genauerem Äquatorumfang rund 1’670 km/h. Das passt zur Grössenordnung eines Überschall-Düsenjets.','B 8',origin='Posten 7')
add('K15','v','Ist ein Längengrad überall ungefähr 111 km breit?','Nein. Am Äquator ungefähr 111 km; zu den Polen nimmt der Abstand zwischen Meridianen ab. Die Näherung lautet 111 km × cos(Breite). An den Polen treffen alle Meridiane zusammen.','B 1–3, 8',origin='Transfer aus dem Gradnetz')
add('K16','v','Welche ungefähren Koordinaten haben Athen, Warschau, Lissabon und Palermo?','Athen: 37°59′ N / 23°44′ E; Warschau: 52°14′ N / 21°01′ E; Lissabon: 38°43′ N / 9°08′ W; Palermo: 38°07′ N / 13°22′ E.','B 8',origin='Posten 5',note='Gerundete Stadtzentrumswerte zur Orientierung. Der im Auftrag verwendete Atlas-Ausschnitt fehlt; keine sekundengenaue Musterlösung aus dieser Karte.')
add('K17','v','Wie viele Breiten und Längen gibt es eigentlich?','Die Schulunterteilung verwendet 90° nach Norden und Süden sowie 180° nach Osten und Westen. Zwischen ganzzahligen Werten sind beliebig viele Zwischenwerte möglich; das Gradnetz besteht nicht nur aus einer festen Anzahl Linien.','B 4',note='180° E und 180° W bezeichnen denselben Meridian. Bei der Anzahl ganzzahliger Linien muss man Äquator, Pole und Doppelzählungen beachten.')
section('L07','Atlas-Posten','Die Tour d’Europe und geografische Grenzen mit dem Gradnetz erschliessen.')
for id,n,coord,a in [
 ('P01','Theater','55°45′ N / 37°37′ E','Gesucht ist das Bolschoi-Theater in Moskau; im Rätsel passt «Bolschoi».'),
 ('P02','Observatorium','51°30′ N / 0°','Greenwich bei London, bekannt für das historische Royal Observatory und den Nullmeridian.'),
 ('P03','Tempelanlage','37°58′ N / 23°44′ E','Die Akropolis in Athen; im Kreuzworträtsel passt «Akropolis».'),
 ('P04','Land','42°30′ N / 1°30′ E','Andorra, der kleine Staat in den Pyrenäen zwischen Frankreich und Spanien.'),
 ('P05','Halbinsel','45° N / 35° E','Die Krim am Schwarzen Meer. Die Aufgabe fragt nach dem geografischen Namen der Halbinsel.'),
 ('P06','Insel','40° N / 4° E','Menorca, eine Insel der Balearen. Die Gradangaben sind grob gerundet.'),
 ('P07','Ort','47° N / 8°30′ E','Im Rätsel wird «Brunnen» erwartet (sieben Kästchen). Brunnen liegt ungefähr bei 47,00° N / 8,61° E; die angegebene Länge ist grob gerundet.'),
 ('P08','Stadt','52°12′ N / 5°58′ E','Apeldoorn in den Niederlanden; neun Buchstaben im Rätsel.'),
 ('P09','Salzsee','45° N / 60° E','Der Aralsee in Zentralasien. Die Koordinate und das Bild beziehen sich auf das historische Seegebiet; der See ist stark geschrumpft.'),
 ('P10','Inselgruppe','60° N / 1° W','Die Shetland-Inseln nördlich von Schottland. Im Rätsel ist der Bindestrich vorgegeben.'),
 ('P11','Wintersportort','61° N / 10°28′ E','Lillehammer in Norwegen, Austragungsort der Olympischen Winterspiele 1994.'),
 ('P12','Vulkan','63°40′ N / 19° W','Katla in Island. Die Koordinate ist gerundet; der Smithsonian-Katalog nennt 63,633° N / 19,083° W.'),
 ('P13','Stadt','44° N / 10° E','Carrara in Italien; die Stadt ist unter anderem durch Marmor bekannt.')]:
 add(id,'v',f'Tour d’Europe: Welches {n if n=="Land" else "Ziel"} ist bei {coord} gesucht ({n})?',a,'B 6',origin='Posten 1: Tour d’Europe',note='Aus Koordinaten, Bild und Kästchenzahl erschlossen; keine mitgelieferte Lösungsliste.' if id in ['P07','P13'] else '',links='katla' if id=='P12' else '')
add('P14','p','Welches Lösungswort ergibt die Tour d’Europe?','Die markierten Buchstaben lassen sich zu «MERIDIAN» ordnen. Kontrolle: Aralsee liefert A; Shetland-Inseln D und I; Lillehammer I und M; Andorra R; Menorca E; Brunnen N.','B 6',origin='Posten 1: Lösungswort',note='Aus dem sichtbaren Raster und den Ortsnamen rekonstruiert.')
add('P15','v','Welche drei Breitenkreise sind in Posten 2 gesucht?','Westlicher Grenzabschnitt USA/Kanada: 49° N; Tennessee/Alabama: ungefähr 35° N; Ägypten/Sudan: im gemeinten geradlinigen Abschnitt 22° N.','B 7',origin='Posten 2: Breitenkreise',note='Gemeint sind idealisierte Grenzabschnitte, nicht sämtliche Grenzen der genannten Gebiete.')
add('P16','v','Welche drei Meridiane ergeben mit den Breiten aus Posten 2 die Summe 444°?','Alaska/Kanada: 141° W; westlicher gerader Abschnitt Usbekistan/Kasachstan: 56° E; Indonesien/Papua-Neuguinea: 141° E. Kontrolle: 49 + 35 + 22 + 141 + 56 + 141 = 444.','B 7',origin='Posten 2: Meridiane',note='Die Grenze auf Neuguinea weicht beim Fly River vom Meridian ab. Die Prüfsumme addiert Beträge; Himmelsrichtungen bleiben getrennt.')
section('L08','Jahreszeiten','Rotation und Revolution trennen, Achsneigung erklären und Sonnenstände zuordnen.')
add('J01','b','Was ist der Unterschied zwischen Rotation und Revolution?','Rotation ist die Drehung um die eigene Achse und erklärt den täglichen Wechsel von Tag und Nacht. Revolution ist der Umlauf der Erde um die Sonne in ungefähr einem Jahr.','A 9; B 9–10')
add('J02','b','Um wie viel ist die Erdachse geneigt?','Etwa 23,4° gegenüber der Senkrechten auf der Erdbahnebene. Gegenüber der Ebene selbst beträgt der Winkel etwa 66,6°. Im Unterricht wird häufig mit 23,5° und 66,5° gerundet.','A 9; B 9–10',links='achse')
add('J03','v','Wie entstehen die Jahreszeiten?','Die geneigte Erdachse behält während eines Umlaufs näherungsweise ihre Richtung im Raum bei. Dadurch erhält jede Halbkugel zeitweise steilere Sonnenstrahlen und längere Tage: Sommer. Auf der anderen Halbkugel ist gleichzeitig Winter.','A 9–10; B 9–10')
add('J04','b','Weshalb ist die Nähe zur Sonne nicht die Ursache unseres Sommers?','Die Erde ist Anfang Januar im Perihel der Sonne am nächsten und Anfang Juli im Aphel am weitesten entfernt. Auf der Nordhalbkugel ist es dabei Winter bzw. Sommer. Entscheidend sind Achsneigung, Sonnenhöhe und Tageslänge.','B 9')
add('J05','b','Was bedeuten Perihel und Aphel?','Perihel ist der sonnennächste, Aphel der sonnenfernste Punkt einer Umlaufbahn. Die genauen Kalendertage schwanken von Jahr zu Jahr; als Merkwerte gelten Anfang Januar und Anfang Juli.','B 9')
add('J06','v','Was ist mit Ekliptik gemeint?','Astronomisch ist die Ekliptik die scheinbare jährliche Sonnenbahn am Himmel. Die Erdbahnebene wird Ekliptikebene genannt; das Dossier verwendet «Ekliptik» vereinfacht auch für diese Ebene bzw. Bahn.','A 9; B 9',note='Eine Bahnkurve und die Ebene, in der sie liegt, sind nicht identisch.',links='achse')
add('J07','v','Warum erwärmt steile Sonneneinstrahlung eine Fläche stärker?','Die gleiche Strahlungsmenge verteilt sich bei steilem Einfall auf eine kleinere Bodenfläche. Bei flachem Einfall verteilt sie sich auf eine grössere Fläche. Auch die Tageslänge beeinflusst die tägliche Energiemenge.','B 9')
add('J08','b','Was bedeutet Zenitstand?','Die Sonne steht senkrecht über dem Beobachtungsort, also 90° über dem Horizont. Ein senkrechter Stab wirft dann idealisiert keinen seitlichen Schatten.','B 9–10')
add('J09','b','Wo kann die Sonne im Zenit stehen?','Nur zwischen den Wendekreisen, ungefähr 23,4° N und 23,4° S, einschliesslich ihrer Grenzen. In der Schweiz erreicht die Sonne nie den Zenit.','B 9–10')
add('J10','b','Welche fünf wichtigen Breitenkreise folgen von Norden nach Süden?','Nördlicher Polarkreis: ca. 66,6° N; nördlicher Wendekreis: ca. 23,4° N; Äquator: 0°; südlicher Wendekreis: ca. 23,4° S; südlicher Polarkreis: ca. 66,6° S.','B 10',origin='Beschriftung A–E von Nord nach Süd')
add('J11','b','Wo steht die Sonne zu den Sonnenwenden und Tagundnachtgleichen im Zenit?','Um den 20./21. März und 22./23. September über dem Äquator; um den 20./21. Juni über dem nördlichen Wendekreis; um den 21./22. Dezember über dem südlichen Wendekreis.','B 9–10')
add('J12','b','Was sind Polartag und Polarnacht?','Polartag bzw. Mitternachtssonne: Die Sonne geht mindestens 24 Stunden nicht unter. Polarnacht: Die Sonne steigt mindestens 24 Stunden nicht über den Horizont. Dämmerung kann dennoch auftreten.','B 10',note='Polarnacht bedeutet nicht zwingend 24 Stunden völlige Dunkelheit.')
add('J13','v','Warum liegen die Polarkreise bei ungefähr 66,6°?','90° − 23,4° Achsneigung = 66,6°. Im vereinfachten geometrischen Modell beginnt hier zur jeweiligen Sonnenwende mindestens ein ganzer Tag ohne Sonnenuntergang bzw. Sonnenaufgang.','B 10')
add('J14','v','Wie lange dauern Polartag und Polarnacht an den Polen?','Jeweils ungefähr ein halbes Jahr. Am Nordpol herrscht ungefähr von März bis September Polartag, am Südpol im gleichen Zeitraum Polarnacht. Brechung und Sonnenscheibengrösse verschieben die beobachteten Grenzen.','B 10')
add('J15','b','Wann beginnen die astronomischen Jahreszeiten auf der Nordhalbkugel?','Frühling um 20./21. März, Sommer um 20./21. Juni, Herbst um 22./23. September und Winter um 21./22. Dezember. Jede Jahreszeit endet mit dem Beginn der nächsten; im Süden sind sie entgegengesetzt.','B 10',note='Die Daten variieren mit Jahr und Zeitzone. Meteorologische Jahreszeiten beginnen dagegen jeweils am Monatsersten.')
add('J16','b','Was bedeutet Äquinoktium, und wann sind die Tage am längsten oder kürzesten?','Äquinoktium bedeutet Tagundnachtgleiche im März und September. In Mitteleuropa ist der Tag zur Juni-Sonnenwende am längsten und zur Dezember-Sonnenwende am kürzesten.','B 10')
add('J17','p','Sind Tag und Nacht am Äquinoktium beobachtet exakt zwölf Stunden lang?','Im geometrischen Modell ungefähr ja. Beobachtet wirken Lichtbrechung und die Ausdehnung der Sonnenscheibe: Sonnenaufgang zählt ab dem ersten sichtbaren Rand. Deshalb ist der helle Tag meist etwas länger.','B 10',note='«Gleich lang» ist eine Modellnäherung.')
add('J18','v','Weshalb gibt es Schaltjahre?','Das tropische Jahr dauert etwa 365,2422 Tage, nicht genau 365. Der zusätzliche Tag gleicht die Differenz aus: durch 4 teilbare Jahre sind Schaltjahre, Jahrhundertjahre nur dann, wenn sie auch durch 400 teilbar sind.','B 9',note='«Alle vier Jahre» lässt die Jahrhundertregel weg: 2000 war ein Schaltjahr, 2100 wird keines sein.')
add('J19','p','Was beschreibt der Zeitraum von etwa 26’000 Jahren bei der Erdachse?','Die Präzession: Die Richtung der Erdachse vollführt langfristig eine Kreiselbewegung. Das ist nicht dasselbe wie die periodische Veränderung des Neigungswinkels. Für die Erklärung eines einzelnen Jahres bleibt die Achsenrichtung näherungsweise konstant.','A 9',note='Das Dossier vermischt Achsenrichtung und Neigungswinkel.',links='achse')
add('J20','p','Berechne die Mittagssonnenhöhe bei 47° N zur Tagundnachtgleiche sowie im Juni und Dezember.','Näherung: Höhe = 90° − |Breite − Sonnendeklination|. Tagundnachtgleiche: 43°. Juni mit +23,4°: 66,4°. Dezember mit −23,4°: 19,6°.','B 9–10',origin='Vertiefende Anwendung der Geometrie')
section('L09','Ortszeit & Zeitzonen','Ortszeit von Zonenzeit unterscheiden und Zeitdifferenzen nachvollziehbar berechnen.')
add('Z01','b','Welche Winkelgeschwindigkeit ergibt sich aus 360° in 24 Stunden?','15° pro Stunde. Für 1° benötigt die Drehung 4 Minuten; 1′ Länge entspricht 4 Sekunden mittlerer Ortszeit.','B 11')
add('Z02','b','Was ist die wahre Ortszeit (WOZ)?','Sie richtet sich nach dem tatsächlich beobachteten Sonnenstand. Wenn die Sonne den örtlichen Meridian beim oberen täglichen Durchgang passiert, ist es 12 Uhr wahre Ortszeit.','B 11')
add('Z03','v','Wie unterscheiden sich wahre und mittlere Ortszeit?','Die wahre Ortszeit folgt der realen Sonne. Die mittlere Ortszeit folgt einer gedachten gleichmässig laufenden Sonne. Wegen elliptischer Erdbahn und Achsneigung entstehen im Jahreslauf Unterschiede, die durch die Zeitgleichung beschrieben werden.','B 11')
add('Z04','v','Chur liegt bei 9°31′ E, Solothurn bei 7°31′ E. Welche Ortszeitdifferenz ergibt sich?','Die Längendifferenz ist 2°. 2 × 4 min = 8 Minuten. Chur liegt östlicher und ist in der mittleren Ortszeit 8 Minuten voraus. Beide Orte haben dennoch dieselbe gesetzliche Schweizer Uhrzeit.','B 11',origin='Ortszeitrechnung Chur–Solothurn')
add('Z05','v','Bern liegt vereinfacht bei 7,5° E. Wie gross ist seine mittlere Ortszeitdifferenz zu Greenwich?','7,5 × 4 = 30 Minuten. Die mittlere Ortszeit von Bern liegt 30 Minuten vor jener von Greenwich.','B 11',origin='Ortszeitrechnung Bern')
add('Z06','b','Warum gibt es Zeitzonen?','Einheitliche gesetzliche Uhrzeiten erleichtern Fahrpläne, Kommunikation und Verwaltung. Das theoretische Modell hat 24 Zonen zu je 15°. Tatsächliche Grenzen folgen politischen und praktischen Entscheidungen.','B 11–12')
add('Z07','b','Was bedeuten UTC, GMT, WEZ, MEZ und MESZ?','UTC: koordinierte Weltzeit. GMT: Greenwich Mean Time, im Schulrechnen gleicher Stundenoffset wie UTC. WEZ: Westeuropäische Zeit, UTC+0. MEZ: Mitteleuropäische Zeit, UTC+1. MESZ: Mitteleuropäische Sommerzeit, UTC+2.','B 12',links='tz')
add('Z08','v','In Wattwil ist es 12:00 gesetzliche Uhrzeit. Wie spät ist es in UTC, MEZ und MESZ?','Bei Schweizer Winterzeit: UTC/WEZ 11:00, MEZ 12:00, MESZ rechnerisch 13:00. Bei Schweizer Sommerzeit: UTC/WEZ 10:00, MEZ rechnerisch 11:00, MESZ 12:00.','B 12',note='Die Aufgabe sagt «Ortszeit». Hier ist ausdrücklich die gesetzliche Uhrzeit gemeint; ohne Jahreszeit gibt es zwei Möglichkeiten.')
add('Z09','p','Und wenn mit 12 Uhr in Wattwil wirklich mittlere Ortszeit gemeint ist? Nutze 9°05′ E.','9°05′ × 4 min/Grad = 36 min 20 s Vorsprung gegenüber Greenwich. Bei 12:00 mittlerer Ortszeit in Wattwil ist die mittlere Greenwich-Zeit ungefähr 11:23:40. Bei wahrer Ortszeit braucht man zusätzlich Datum und Zeitgleichung.','B 7, 11–12',note='Sonnenzeit und gesetzliche Zonenzeit dürfen nicht gleichgesetzt werden; die Annäherung ignoriert kleine Unterschiede zu UTC.')
add('Z10','v','Was fällt an der mitteleuropäischen Zeitzone auf?','Sie reicht deutlich über einen idealen 15°-Streifen hinaus. Politische und wirtschaftliche Abstimmung führen dazu, dass weit westlich und östlich gelegene Orte dieselbe gesetzliche Uhrzeit verwenden.','B 12',origin='Analyse der MEZ')
add('Z11','v','Warum gibt es halbe und Viertelstunden-Zeitzonen?','Staaten wählen eine zum Land und seiner Geschichte passende Zeit. Beispiele: Indien UTC+5:30, Iran UTC+3:30 und Nepal UTC+5:45. Zeitzonen müssen keine ganzen Stunden auseinanderliegen.','B 12',links='asien')
add('Z12','p','Ist Nordkorea weiterhin eine halbe Stunde gegenüber Südkorea versetzt?','Nein. Nordkorea verwendete ab 2015 UTC+8:30 und kehrte im Mai 2018 zu UTC+9 zurück. Die Frage im Dossier bezieht sich auf eine historische Sonderzone.','B 12',note='Historischen Kartenstand von heutigen Regeln trennen. Nepal bleibt ein Beispiel für einen Viertelstundenoffset.',links='asien')
add('Z13','p','Welches Land und welcher Kontinent haben «die meisten Zeitzonen»?','Die Antwort braucht eine Zählregel. Unter zusammenhängenden Staatsgebieten ist Russland mit elf Zonen das typische Schulbeispiel. Mit Überseegebieten wird oft Frankreich genannt. Bei Kontinenten wird meist Asien erwartet; Inselzuordnung und Definition der Zeitzone beeinflussen den Vergleich.','B 12',note='Die im Auftrag genannte Atlas-/Buchkarte liegt nicht vor. Ihre konkrete Zählung kann deshalb nicht zuverlässig rekonstruiert werden.',status='offen')
add('Z14','p','Wie viele Zeitzonen haben Grönland und Afrika?','Es gibt ohne Datum und Zählregel keine eindeutige Zahl: Verschiedene Regelgebiete können zeitweise denselben UTC-Offset haben. Inseln und Sommerzeit verändern die Zählung. Grönlands Regeln wurden seit dem Kartenstand verändert.','B 12',note='Die erwartete Zahl muss an der fehlenden Atlas-Karte mit Datum, Inselumfang und Zählweise ermittelt werden. Diese Karte bleibt eine offene Quellenfrage.',links='amerika',status='offen')
add('Z15','v','Wie rechnet man zwischen zwei Zeitzonen sicher um?','Zuerst Ortszeit minus UTC-Offset des Ausgangsortes = UTC. Danach UTC plus Zieloffset = Zielzeit. Berücksichtige Datum, Sommerzeit und einen möglichen Tageswechsel.','B 12–15')
add('Z16','p','Warum beweist eine ähnliche Zeitzone nicht, dass zwei Orte nahe beieinander liegen?','Zeitzonen folgen vor allem der geografischen Länge und politischen Entscheidungen. Zwei Orte können auf ähnlicher Länge, aber sehr weit auseinander in Nord-Süd-Richtung liegen.','B 11–12',origin='Transfer')
section('L10','Zeitrechnen & Flüge','Übertragungszeiten und Flugaufgaben einschliesslich Sommerzeit und Datumswechsel lösen.')
# Historischer Zeitpunkt der Originalaufgabe: 31.08.2023 20:00 MESZ = 18:00 UTC.
for i,(city,offset,time) in enumerate([('Tokyo','UTC+9','03:00 am 1. September'),('Shanghai','UTC+8','02:00 am 1. September'),('Johannesburg','UTC+2','20:00 am 31. August'),('Rio de Janeiro','UTC−3','15:00 am 31. August'),('Lima','UTC−5','13:00 am 31. August'),('New York','UTC−4','14:00 am 31. August'),('Los Angeles','UTC−7','11:00 am 31. August'),('Anchorage','UTC−8','10:00 am 31. August'),('Oslo','UTC+2','20:00 am 31. August'),('Thule / Pituffik','UTC−3','15:00 am 31. August')],1):
 add(f'T{i:02}','v',f'Weltklasse Zürich: 31.8.2023, 20:00 MESZ. Wie spät ist es in {city}?',f'{time} 2023. Rechnung: 20:00 MESZ = 18:00 UTC; {city} verwendet an diesem Datum {offset}.','B 12',origin='Weltklasse Zürich: '+city,links='tz',note='Historischer Termin der Vorlage; die damaligen Sommerzeitregeln sind berücksichtigt.' if i in [1,10] else '')
add('T11','p','Omsk 18:45, Flugzeit 6 h 40 min, Ziel Jakutsk: Welche Ankunftszeit?','Unter der Annahme Omsk UTC+6 und Jakutsk UTC+9: 18:45 + 6:40 + 3:00 = 04:25 am Folgetag. Die Streckenlänge ist für diese Zeitrechnung nicht nötig.','B 12',origin='Flug Omsk–Jakutsk',note='Die Vorlage nennt kein Jahr. Verwendet werden die für 2026 geltenden Zonenregeln.',links='tz')
add('T12','p','Abflug Omsk 14:25, Ankunft Jekaterinburg 14:20. Wie lange dauerte der Flug?','Omsk UTC+6, Jekaterinburg UTC+5: Abflug 08:25 UTC, Ankunft 09:20 UTC. Die Flugzeit beträgt 55 Minuten.','B 12',origin='Flug Omsk–Jekaterinburg',note='Annahme: Ankunft am selben lokalen Tag; Zonenregeln von 2026.',links='tz')
add('T13','p','Anadyr: 3. Juni, 15:00. Wie spät ist es gleichzeitig in der Schweiz?','Mit Anadyr UTC+12 und der Schweiz im Juni UTC+2: 15:00 − 12 h + 2 h = 05:00 am 3. Juni.','B 13',origin='Telefonat Anadyr–Schweiz',note='Die undatierte Jahresangabe wird mit den Regeln von 2026 ergänzt.',links='tz')
add('T14','p','Petropawlowsk-Kamtschatski 08:15 → Moskau 15:00, fünf Stunden Zwischenhalt: Wie viel reine Flugzeit?','Petropawlowsk-Kamtschatski UTC+12, Moskau UTC+3. Moskauer Ankunft 15:00 entspricht 00:00 am Folgetag am Startort. Gesamtzeit 15 h 45 min, minus 5 h Aufenthalt = 10 h 45 min reine Flugzeit.','B 13',origin='Flug via Nowosibirsk',note='Gemeint ist ausdrücklich Petropawlowsk-Kamtschatski. Annahme: Moskau-Ankunft am selben lokalen Datum; Regeln von 2026.',links='tz')
add('T15','p','Zürich 12:40 → Moskau 18:45, Strecke 2’600 km. Welche Durchschnittsgeschwindigkeit?','Im Schweizer Sommer (UTC+2, Moskau UTC+3): Flugzeit 5 h 05 min; 2’600 ÷ (5 + 5/60) ≈ 511 km/h. Im Winter (Zürich UTC+1): Flugzeit 4 h 05 min; Geschwindigkeit ≈ 637 km/h.','B 13',origin='Geschwindigkeit Zürich–Moskau',note='Ohne Datum ist die Vorlage mehrdeutig. Beide Ergebnisse setzen Ankunft am selben lokalen Tag und konstante Zonenregeln wie 2026 voraus.',links='tz')
add('T16','p','Wellington: 1. Januar 2024 um 09:00. Datum und Uhrzeit in San Francisco?','Wellington hat UTC+13, San Francisco UTC−8. 09:00 − 21 h = 12:00 am 31. Dezember 2023.','B 15',origin='Datumsrechnung 1',links='pazifik amerika')
add('T17','p','Tokyo: Abflug 12. Mai 2024, 12:00. Flugzeit 5 h nach Anchorage. Wann ist die Ankunft?','Tokyo UTC+9: Start 03:00 UTC; plus 5 h = 08:00 UTC am 12. Mai. Anchorage UTC−8: 00:00 am 12. Mai 2024.','B 15',origin='Datumsrechnung 2',note='Anchorage hat im Mai Sommerzeit. Kein zusätzlicher Tag darf nach der korrekten UTC-Umrechnung nochmals abgezogen werden.',links='amerika asien')
add('T18','p','Port Vila: 11. November 2023, 23:00. Flugzeit 8 h 30 min nach Avarua. Wann landet man?','Port Vila UTC+11: Start 12:00 UTC am 11. November. Ankunft 20:30 UTC; Avarua UTC−10: 10:30 am 11. November 2023.','B 15',origin='Datumsrechnung 3',links='pazifik')
section('L11','Datumsgrenze & Quellenkritik','Datumswechsel erklären und historische Zeitzonenentscheidungen einordnen.')
add('D01','b','Wozu braucht man eine Datumsgrenze?','Die örtlichen Kalenderdaten müssen auf einer umrundbaren Erde zusammenpassen. Beim Überschreiten der Datumsgrenze wird deshalb das Datum angepasst. Es handelt sich um eine Kalenderregel, nicht um eine Zeitreise.','B 14')
add('D02','b','Wo verläuft die Datumsgrenze?','Überwiegend im Pazifik nahe dem 180°-Meridian. Sie weicht davon ab, damit Staaten und Inselgruppen möglichst einheitliche Kalenderdaten verwenden können.','B 14')
add('D03','b','Was geschieht beim Überqueren der Datumsgrenze nach Westen oder Osten?','Nach Westen, etwa von Alaska Richtung Russland: einen Kalendertag hinzufügen. Nach Osten, etwa von Russland nach Alaska: einen Kalendertag abziehen. Bei konkreten Reisen zusätzlich Reisezeit und Zonenoffsets beachten.','B 14')
add('D04','v','Was geschah beim Datumswechsel Samoas Ende 2011?','Auf Donnerstag, den 29. Dezember 2011, folgte Samstag, der 31. Dezember. Der 30. Dezember wurde ausgelassen; Samoa wechselte auf die Seite mit dem früher beginnenden Kalendertag.','B 14–15',note='Samoa liegt seit dem Wechsel auf der westlichen Datumsseite. Die gegenteilige Passage im Dossier ist überholt.',links='pazifik')
add('D05','v','Welchen wirtschaftlichen Vorteil versprach sich Samoa vom Wechsel?','Die Arbeitstage stimmen seither besser mit wichtigen Partnern wie Australien und Neuseeland überein. Das erleichtert Handel und Kommunikation, weil weniger Geschäftstage durch unterschiedliche Wochenenden verloren gehen.','B 15',origin='Samoa: Begründung',links='pazifik')
add('D06','v','Was zeigen die beiden Venezuela-Artikel von 2007 und 2016?','2007 wurde die Uhr um eine halbe Stunde auf UTC−4:30 zurückgestellt. 2016 wurde diese Änderung rückgängig gemacht. Die Artikel zeigen, dass Zeitzonen politische Entscheidungen sind und historische Zeitangaben datiert werden müssen.','B 13',origin='Vergleich der Zeitungstexte')
add('D07','p','Warum darf man eine alte Zeitzonenkarte nicht für jede Flugrechnung verwenden?','Sommerzeit und gesetzliche Offsets können sich ändern. Man braucht den Ort, das Datum und die damals geltenden Regeln. Erst dann lassen sich beide Uhrzeiten auf UTC beziehen und zuverlässig vergleichen.','B 12–15',links='tz')
add('D08','p','Welche Unterrichtsinhalte und Prüfungsziele sind durch die beiden PDFs nicht belegt?','Ein separates Prüfungslernzielblatt liegt nicht vor. Magnetfeld und Kartografie werden im Inhaltsverzeichnis angekündigt, ihre Kapitel sind in diesen beiden Ausschnitten aber nicht enthalten. Die Lernziele der Kartei sind aus dem vorhandenen Stoff abgeleitet.','A 1; B 15',origin='Umfang der Ressourcen',note='Die Kartei beansprucht keine Abdeckung fehlender Kapitel oder eines unbekannten Prüfungsumfangs.')
for c in cards:
 if c['id']=='J10':
  c['image']='breitenkreise.svg'
  c['imageAlt']='Erdkugel mit fünf Breitenkreisen, von Norden nach Süden A bis E.'
  c['imageCaption']='Eigene Skizze: Benenne A bis E und die zugehörigen Winkel.'
  c['question']='Benenne die Breitenkreise A bis E von Norden nach Süden und ihre Winkel.'
data=dict(title='Geografie zum Wenden',version=1,sources=sources,goals=goals,cards=cards)
(root/'cards.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
coverage=[dict(id=g['id'],description=g['description'],cards=[c['id'] for c in cards if g['id'] in c['goals']]) for g in goals]
(root/'coverage.json').write_text(json.dumps(coverage,ensure_ascii=False,indent=2)+'\n')
lines=['# Abdeckung der Unterlagen','','A = Geografie Einführung 2026.pdf (10 PDF-Seiten; gedruckt 1–9 nach Titelblatt).','B = Einführung GG.pdf (15 PDF-Seiten; gedruckt 10–24).','Seitenangaben in der Kartei beziehen sich auf PDF-Seiten. Lernziele sind redaktionell abgeleitet, keine offiziellen Prüfungsziele.','','| Karte | Aufgabe / Herkunft | Quelle | Niveau | Status |','|---|---|---|---|---|']
for c in cards: lines.append(f"| {c['id']} | {c['origin']} | {c['pages']} | {c['level']} | {c['status']} |")
(root/'docs/ABDECKUNG.md').write_text('\n'.join(lines)+'\n')
print(len(cards),'Karten',len(goals),'Lernziele')
